export const GET_ALL_TASKS = "GET_ALL_TASKS"
export const CREATE_TASK = "CREATE_TASK" 

export const UPDATE_TASK = "UPDATE_TASK"
export const DELETE_TASK = "DELETE_TASK"
export const GET_DELETED_TASKS = "GET_DELETED_TASKS"